version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - type: bind
        source: /c/codeK/www/mysql #change directory if OS is Linux/Mac/Win
        target: /var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - default

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
    - type: bind
      source: /c/codeK/www/wp #change directory if OS is Linux/Mac/Win
      target: /var/www/html
    networks:
      - default

  phpmyadmin:
    depends_on:
      - db
      - wordpress
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8180:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 
    networks:
      - default


